name: Imtiaz Willems
favicon: null
layout_spectrum: 1
typography_spectrum: 0.16968
title: Imtiaz Willems
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5c6f82'
    - '#222835'
    - '#3d4f60'
    - '#612c3d'
    - '#cb3659'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
